import { useState } from "react";
import {
  useReactTable,
  getCoreRowModel,
  flexRender,
  createColumnHelper,
} from "@tanstack/react-table";
import { TableVirtuoso } from "react-virtuoso";
import { Button } from "@/components/ui/button";
import { Download, FileText, FileSpreadsheet, ChevronDown, ChevronUp } from "lucide-react";
import type { Report, RecentReportsTableProps } from "../types/reports.types";
import { formatDateTime } from "../../../../utils/date";



const columnHelper = createColumnHelper<Report>();

const columns = [
  columnHelper.accessor("name", {
    header: "Report Name",
    cell: (info) => {
      const format = info.row.original.format;
      return (
        <div className="flex items-center gap-2">
          {format === "PDF" ? (
            <FileText className="w-4 h-4 text-rose-400 flex-shrink-0" />
          ) : (
            <FileSpreadsheet className="w-4 h-4 text-emerald-500 flex-shrink-0" />
          )}
          <span className="font-medium text-sm text-gray-900">{info.getValue()}</span>
        </div>
      );
    },
  }),
  columnHelper.accessor("generatedAt", {
    header: "Generated On",
    cell: (info) => (
      <span className="text-sm text-gray-600">{formatDateTime(info.getValue())}</span>
    ),
  }),
  columnHelper.accessor("period", {
    header: "Period",
    cell: (info) => (
      <span className="text-sm text-gray-600">{info.getValue()}</span>
    ),
  }),
  columnHelper.accessor("format", {
    header: "Format",
    cell: (info) => (
      <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
        info.getValue() === "PDF"
          ? "bg-rose-100 text-rose-700"
          : "bg-emerald-100 text-emerald-700"
      }`}>
        {info.getValue()}
      </span>
    ),
  }),
  columnHelper.accessor("generatedBy", {
    header: "Generated By",
    cell: (info) => (
      <span className="text-sm text-gray-600">{info.getValue()}</span>
    ),
  }),
  columnHelper.display({
    id: "download",
    header: "Download",
    cell: () => (
      <div className="flex justify-center">
        <Button
          size="sm"
          variant="ghost"
          className="h-8 w-8 p-0 text-[#3525CD] hover:text-[#2a1eb0] hover:bg-indigo-50"
        >
          <Download className="w-4 h-4" />
        </Button>
      </div>
    ),
  }),
];



interface VirtualTableProps {
  data: Report[];
  height: number;
}

const VirtualTable = ({ data, height }: VirtualTableProps) => {
  const table = useReactTable({
    data,
    columns,
    getCoreRowModel: getCoreRowModel(),
  });

  const { rows } = table.getRowModel();
  const headerGroups = table.getHeaderGroups();

  return (
    <TableVirtuoso
      data={rows}
      style={{ height }}
      fixedHeaderContent={() =>
        headerGroups.map((headerGroup) => (
          <tr key={headerGroup.id} className="bg-gray-50/80">
            {headerGroup.headers.map((header) => (
              <th
                key={header.id}
                className="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide border-b border-gray-100 whitespace-nowrap"
              >
                {header.isPlaceholder
                  ? null
                  : flexRender(header.column.columnDef.header, header.getContext())}
              </th>
            ))}
          </tr>
        ))
      }
      itemContent={(_, row) => (
        <>
          {row.getVisibleCells().map((cell) => (
            <td key={cell.id} className="px-4 py-3 border-b border-gray-50">
              {flexRender(cell.column.columnDef.cell, cell.getContext())}
            </td>
          ))}
        </>
      )}
      components={{
        Table: ({ style, ...props }) => (
          <table {...props} style={style} className="w-full border-collapse" />
        ),
        TableRow: ({ style, ...props }) => (
          <tr {...props} style={style} className="hover:bg-gray-50/60 transition-colors" />
        ),
      }}
    />
  );
};



const MobileReportRow = ({ report }: { report: Report }) => (
  <div className="p-4 space-y-2">
    <div className="flex items-center justify-between">
      <div className="flex items-center gap-2">
        {report.format === "PDF" ? (
          <FileText className="w-4 h-4 text-rose-400 flex-shrink-0" />
        ) : (
          <FileSpreadsheet className="w-4 h-4 text-emerald-500 flex-shrink-0" />
        )}
        <span className="text-sm font-medium text-gray-900">{report.name}</span>
      </div>
      <Button size="sm" variant="ghost" className="h-8 w-8 p-0 text-[#3525CD] hover:bg-indigo-50">
        <Download className="w-4 h-4" />
      </Button>
    </div>
    <div className="text-xs text-gray-500 space-y-1">
      <div>📅 {formatDateTime(report.generatedAt)}</div>
      <div>📊 {report.period}</div>
      <div>👤 {report.generatedBy}</div>
    </div>
    <span className={`inline-flex px-2 py-0.5 rounded-full text-xs font-medium ${
      report.format === "PDF"
        ? "bg-rose-100 text-rose-700"
        : "bg-emerald-100 text-emerald-700"
    }`}>
      {report.format}
    </span>
  </div>
);



const ROW_HEIGHT = 53;
const HEADER_HEIGHT = 44;
const PREVIEW_COUNT = 5;

export const RecentReportsTable = ({ data }: RecentReportsTableProps) => {
  const [showAll, setShowAll] = useState(false);

  const visibleData = showAll ? data : data.slice(0, PREVIEW_COUNT);
  const hasMore = data.length > PREVIEW_COUNT;


  const tableHeight = visibleData.length * ROW_HEIGHT + HEADER_HEIGHT;

  return (
    <div className="bg-white rounded-lg border border-gray-200 overflow-hidden">

      {/* Header */}
      <div className="px-5 py-4 border-b border-gray-100 flex items-center justify-between bg-gray-50/50">
        <h3 className="font-semibold text-gray-800 text-sm">Recently Generated Reports</h3>
        {hasMore && (
          <span className="text-xs text-gray-400">
            Showing {visibleData.length} of {data.length}
          </span>
        )}
      </div>

  
      <div className="md:hidden divide-y divide-gray-100">
        {visibleData.map((report) => (
          <MobileReportRow key={report.id} report={report} />
        ))}
      </div>


      <div className="hidden md:block">
        <VirtualTable data={visibleData} height={tableHeight} />
      </div>


      {hasMore && (
        <div className="border-t border-gray-100 px-5 py-3 flex items-center justify-center bg-gray-50/30">
          <Button
            variant="ghost"
            size="sm"
            className="text-[#3525CD] text-xs h-8 hover:text-[#2a1eb0] hover:bg-indigo-50 gap-1.5"
            onClick={() => setShowAll((prev) => !prev)}
          >
            {showAll ? (
              <>
                <ChevronUp className="w-3.5 h-3.5" />
                Show Less
              </>
            ) : (
              <>
                <ChevronDown className="w-3.5 h-3.5" />
                View All History ({data.length - PREVIEW_COUNT} more)
              </>
            )}
          </Button>
        </div>
      )}

    </div>
  );
};