// components/RecentReportsTable.tsx
import {
  Table,
  TableHeader,
  TableRow,
  TableHead,
  TableBody,
  TableCell,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Download, FileText, FileSpreadsheet } from "lucide-react";
import { useNavigate } from "react-router-dom";
import type { Report } from "../types/reports.types";
import { formatDateTime } from "../utils/report.utils";

interface RecentReportsTableProps {
  data: Report[];
}

export const RecentReportsTable = ({ data }: RecentReportsTableProps) => {
  const navigate = useNavigate();

  return (
    <div className="bg-white rounded-lg border border-gray-200 overflow-hidden">
      <div className="px-5 py-4 border-b border-gray-100 flex items-center justify-between bg-gray-50/50">
        <h3 className="font-semibold text-gray-800 text-sm">Recently Generated Reports</h3>
        <Button
          variant="ghost"
          size="sm"
          className="text-indigo-600 text-xs h-8"
       onClick={() => navigate("/accountant/reports/history")}
        >
          View All History →
        </Button>
      </div>
{/* MOBILE VIEW */}
<div className="md:hidden divide-y">
  {data.map((report) => (
    <div key={report.id} className="p-4 space-y-2">
      {/* Title + Icon */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          {report.format === "PDF" ? (
            <FileText className="w-4 h-4 text-rose-400" />
          ) : (
            <FileSpreadsheet className="w-4 h-4 text-emerald-500" />
          )}
          <span className="text-sm font-medium text-gray-900">
            {report.name}
          </span>
        </div>

        <Button
          size="sm"
          variant="ghost"
          className="h-8 w-8 p-0 text-indigo-600"
        >
          <Download className="w-4 h-4" />
        </Button>
      </div>

      {/* Details */}
      <div className="text-xs text-gray-500 space-y-1">
        <div>📅 {formatDateTime(report.generatedAt)}</div>
        <div>📊 {report.period}</div>
        <div>👤 {report.generatedBy}</div>
      </div>

      {/* Format Badge */}
      <div>
        <span
          className={`inline-flex px-2 py-0.5 rounded-full text-xs font-medium ${
            report.format === "PDF"
              ? "bg-rose-100 text-rose-700"
              : "bg-emerald-100 text-emerald-700"
          }`}
        >
          {report.format}
        </span>
      </div>
    </div>
  ))}
</div>
     <div className="hidden md:block overflow-x-auto">
        <Table>
          <TableHeader>
            <TableRow className="bg-gray-50/50 hover:bg-gray-50/50">
              <TableHead className="text-xs font-semibold text-gray-500 uppercase">Report Name</TableHead>
              <TableHead className="text-xs font-semibold text-gray-500 uppercase">Generated On</TableHead>
              <TableHead className="text-xs font-semibold text-gray-500 uppercase">Period</TableHead>
              <TableHead className="text-xs font-semibold text-gray-500 uppercase">Format</TableHead>
              <TableHead className="text-xs font-semibold text-gray-500 uppercase">Generated By</TableHead>
              <TableHead className="text-xs font-semibold text-gray-500 uppercase text-center">Download</TableHead>
            </TableRow>
          </TableHeader>

          <TableBody>
            {data.map((report) => (
              <TableRow key={report.id} className="hover:bg-gray-50/50 border-b border-gray-50 last:border-0">
                <TableCell className="font-medium text-sm text-gray-900">
                  <div className="flex items-center gap-2">
                    {report.format === "PDF" ? (
                      <FileText className="w-4 h-4 text-rose-400 flex-shrink-0" />
                    ) : (
                      <FileSpreadsheet className="w-4 h-4 text-emerald-500 flex-shrink-0" />
                    )}
                    {report.name}
                  </div>
                </TableCell>
                <TableCell className="text-sm text-gray-600">
                  {formatDateTime(report.generatedAt)}
                </TableCell>
                <TableCell className="text-sm text-gray-600">{report.period}</TableCell>
                <TableCell>
                  <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                    report.format === "PDF"
                      ? "bg-rose-100 text-rose-700"
                      : "bg-emerald-100 text-emerald-700"
                  }`}>
                    {report.format}
                  </span>
                </TableCell>
                <TableCell className="text-sm text-gray-600">{report.generatedBy}</TableCell>
                <TableCell className="text-center">
                  <Button
                    size="sm"
                    variant="ghost"
                    className="h-8 w-8 p-0 text-indigo-600 hover:text-indigo-700 hover:bg-indigo-50"
                  >
                    <Download className="w-4 h-4" />
                  </Button>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </div>
  );
};