import type { ProfileData } from "../types/profile.types";

export const mockProfileData: ProfileData = {
  student: {
    id: "STU-001",
    name: "Ravi Kumar",
    admissionNo: "ADM-001",
    rollNo: "01",
    class: "10A",
    email: "ravi.kumar@school.com",
    phone: "+91 98765 43210",
    dateOfBirth: "2009-03-12",
    gender: "male",
    status: "ACTIVE",
    address: "Plot 12, Hanamkonda Urban, Warangal — 506001",
    emergencyContact: {
      name: "Suresh Kumar",
      phone: "+91 98765 43211",
      relationship: "Father",
    },
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=RaviKumar",
  },
  academic: {
    class: "10A",
    section: "A",
    rollNumber: "01",
    admissionNumber: "ADM-001",
    academicYear: "2024-25",
    board: "CBSE",
    classRoom: "Room 501",
    stream: "Science",
    subjects: ["Mathematics", "Physics", "Chemistry", "Biology", "English", "Hindi"],
  },
  personal: {
    dateOfBirth: "2009-03-12",
    gender: "Male",
    bloodGroup: "B+",
    age: "16 years",
    fatherName: "Suresh Kumar",
    fatherPhone: "+91 98765 43210",
    motherName: "Lakshmi Devi",
    motherPhone: "+91 87654 32109",
    fullAddress: "Plot 12, Hanamkonda Urban, Warangal — 506001",
  },
  downloads: [
    {
      id: "doc-1",
      title: "Latest Report Card — 2024-25",
      size: "1.2 MB",
      type: "report_card",
      downloadUrl: "/downloads/report-card-2024-25.pdf",
      lastUpdated: "2024-04-01",
    },
    {
      id: "doc-2",
      title: "Student ID Card",
      size: "0.8 MB",
      type: "id_card",
      downloadUrl: "/downloads/student-id-card.pdf",
      lastUpdated: "2024-06-01",
    },
    {
      id: "doc-3",
      title: "Latest Fee Receipt — RCP-2025-0823",
      size: "0.5 MB",
      type: "certificate",
      downloadUrl: "/downloads/fee-receipt-2025.pdf",
      lastUpdated: "2025-01-15",
    },
  ],
};