import type { AttendancePageData } from "../types/attendance.types";

export const MOCK_ATTENDANCE_DATA: AttendancePageData = {
  date: "Monday, 7 April 2025",
  whatsappNumber: "+91 90000 12345",
  stats: {
    totalPresent: 318,
    presentDelta: "+2.4%",
    totalAbsent: 24,
    absentDelta: "-0.8%",
    classesMarked: 12,
    totalClasses: 15,
    alertsSent: 24,
    totalAlerts: 24,
  },
  rows: [
    {
      id: "6a",
      cls: "6A",
      section: "6",
      teacherInitials: "PR",
      teacherName: "Priya Reddy",
      total: 34,
      present: 32,
      absent: 2,
      status: "MARKED",
      method: "WhatsApp",
      alertsSent: "2/2",
    },
    {
      id: "6b",
      cls: "6B",
      section: "6",
      teacherInitials: "SR",
      teacherName: "Sita Rao",
      total: 32,
      present: 30,
      absent: 2,
      status: "MARKED",
      method: "Web Form",
      alertsSent: "2/2",
    },
    {
      id: "7a",
      cls: "7A",
      section: "7",
      teacherInitials: "KK",
      teacherName: "Kiran Kumar",
      total: 30,
      present: 28,
      absent: 2,
      status: "MARKED",
      method: "WhatsApp",
      alertsSent: "2/2",
    },
    {
      id: "8a",
      cls: "8A",
      section: "8",
      teacherInitials: "SM",
      teacherName: "Suresh M",
      total: 30,
      present: null,
      absent: null,
      status: "NOT_MARKED",
      method: null,
      alertsSent: null,
    },
    {
      id: "9a",
      cls: "9A",
      section: "9",
      teacherInitials: "RT",
      teacherName: "Raju T",
      total: 29,
      present: null,
      absent: null,
      status: "NOT_MARKED",
      method: null,
      alertsSent: null,
    },
    {
      id: "10a",
      cls: "10A",
      section: "10",
      teacherInitials: "VR",
      teacherName: "Venkat R",
      total: 33,
      present: null,
      absent: null,
      status: "NOT_MARKED",
      method: null,
      alertsSent: null,
    },
  ],
};

export const AVATAR_COLORS: Record<string, string> = {
  PR: "bg-purple-100 text-purple-700",
  SR: "bg-sky-100 text-sky-700",
  KK: "bg-teal-100 text-teal-700",
  SM: "bg-orange-100 text-orange-700",
  RT: "bg-rose-100 text-rose-700",
  VR: "bg-green-100 text-green-700",
};