// Mock data for Student Dashboard
export const mockStudentDashboard = {
  student: {
    id: "STU001",
    name: "Ravi",
    className: "Class 10A",
    rollNo: "01",
    schoolName: "Hamankonda Public School",
    avatarUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=Ravi",
  },
  stats: {
    todayStatus: "PRESENT" as const,
    checkedInAt: "08:15 AM",
    attendanceMonth: {
      month: "April",
      year: 2024,
      days: [
        { date: 1, status: "PRESENT" },
        { date: 2, status: "ABSENT" },
        { date: 3, status: "PRESENT" },
        { date: 4, status: "HOLIDAY" },
        { date: 5, status: "PRESENT" },
        { date: 8, status: "ABSENT" },
        { date: 9, status: "PRESENT" },
        { date: 11, status: "HOLIDAY" },
        { date: 15, status: "PRESENT" },
        { date: 16, status: "PRESENT" },
        { date: 17, status: "PRESENT" },
        { date: 18, status: "ABSENT" },
        { date: 22, status: "PRESENT" },
        { date: 23, status: "PRESENT" },
        { date: 24, status: "PRESENT" },
        { date: 25, status: "ABSENT" },
        { date: 26, status: "HOLIDAY" },
      ],
      percentage: 91.7,
      changeFromLastMonth: 2.4,
    },
    homeworkDueCount: 2,
    submissionPortalActive: true,
    nextExamDaysLeft: 9,
    nextExamName: "Mathematics Finals",
  },
};

export const mockSchedule = {
  date: "2024-04-16",
  slots: [
    {
      kind: "period",
      id: "P1",
      label: "P1",
      startTime: "08:30",
      endTime: "09:20",
      subject: "English Literature",
      teacher: "Ms. Sharma",
    },
    {
      kind: "period",
      id: "P2",
      label: "P2",
      startTime: "09:20",
      endTime: "10:10",
      subject: "Mathematics",
      teacher: "Mr. Reddy",
    },
    {
      kind: "break",
      label: "Short Break (10:10 - 10:25)",
      startTime: "10:10",
      endTime: "10:25",
    },
    {
      kind: "period",
      id: "P3",
      label: "P3",
      startTime: "10:25",
      endTime: "11:15",
      subject: "Science (Physics)",
      teacher: "Dr. Gupta",
    },
    {
      kind: "period",
      id: "P4",
      label: "P4",
      startTime: "11:15",
      endTime: "12:05",
      subject: "Social Studies",
      teacher: "Ms. Devi",
    },
    {
      kind: "break",
      label: "Lunch Interval (12:05 - 12:50)",
      startTime: "12:05",
      endTime: "12:50",
    },
    {
      kind: "period",
      id: "P5",
      label: "P5",
      startTime: "12:50",
      endTime: "13:40",
      subject: "Hindi Language",
      teacher: "Mr. Prasad",
    },
    {
      kind: "period",
      id: "P6",
      label: "P6",
      startTime: "13:40",
      endTime: "14:30",
      subject: "Computer Science",
      teacher: "Ms. Rao",
    },
  ],
};

export const mockHomework = {
  items: [
    {
      id: "HW001",
      subject: "English: Poetry Analysis",
      title: "Due: 20 Apr 2024",
      dueDate: "2024-04-20",
      briefUrl: "https://example.com/hw1.pdf",
    },
    {
      id: "HW002",
      subject: "Mathematics: Quadratic Equations",
      title: "Due: 22 Apr 2024",
      dueDate: "2024-04-22",
      briefUrl: "https://example.com/hw2.pdf",
    },
    {
      id: "HW003",
      subject: "Science: Lab Report",
      title: "Due: 18 Apr 2024",
      dueDate: "2024-04-18",
      briefUrl: "https://example.com/hw3.pdf",
    },
  ],
  totalDue: 3,
};

export const mockResults: any[] = [
  {
    id: "RES001",
    examName: "Unit Test I",
    month: "January",
    year: 2025,
    marksObtained: 387,
    totalMarks: 500,
    rank: 12,
    status: "PASS" as const,
    reportUrl: "https://example.com/result1.pdf",
  },
  {
    id: "RES002",
    examName: "Half Yearly Exam",
    month: "December",
    year: 2024,
    marksObtained: 412,
    totalMarks: 500,
    rank: 8,
    status: "DISTINCTION" as const,
    reportUrl: "https://example.com/result2.pdf",
  },
  {
    id: "RES003",
    examName: "Quarterly Exam",
    month: "November",
    year: 2024,
    marksObtained: 398,
    totalMarks: 500,
    rank: 10,
    status: "PASS" as const,
    reportUrl: "https://example.com/result3.pdf",
  },
];

export const mockAnnouncements = [
  {
    id: "ANN001",
    title: "Annual Sports Day registration now open",
    publishedAt: "2024-04-16T10:30:00Z",
    iconType: "sports" as const,
  },
  {
    id: "ANN002",
    title: "Ambedkar Jayanti: School will remain closed on April 14",
    publishedAt: "2024-04-15T09:15:00Z",
    iconType: "holiday" as const,
  },
  {
    id: "ANN003",
    title: "Parent-Teacher Meeting scheduled for 25th April",
    publishedAt: "2024-04-14T14:20:00Z",
    iconType: "general" as const,
  },
  {
    id: "ANN004",
    title: "Mid-term exams from 1st May to 15th May 2024",
    publishedAt: "2024-04-13T08:00:00Z",
    iconType: "academic" as const,
  },
];

export const mockAttendance = {
  month: "April",
  year: 2024,
  days: [
    { date: 1, status: "PRESENT" },
    { date: 2, status: "ABSENT" },
    { date: 3, status: "PRESENT" },
    { date: 4, status: "HOLIDAY" },
    { date: 5, status: "PRESENT" },
    { date: 8, status: "ABSENT" },
    { date: 9, status: "PRESENT" },
    { date: 11, status: "HOLIDAY" },
    { date: 15, status: "PRESENT" },
    { date: 16, status: "PRESENT" },
    { date: 17, status: "PRESENT" },
    { date: 18, status: "ABSENT" },
    { date: 22, status: "PRESENT" },
    { date: 23, status: "PRESENT" },
    { date: 24, status: "PRESENT" },
    { date: 25, status: "ABSENT" },
    { date: 26, status: "HOLIDAY" },
  ],
  percentage: 91.7,
  changeFromLastMonth: 2.4,
};
