export const plans = [
  {
    name: "Starter",
    annualPrice: "45,000",
    monthlyPrice: "4,500",
    studentLimit: "250",
    pilotFee: "5,000",
    features: [
      { name: "Attendance", enabled: true },
      { name: "Fee Management", enabled: true },
      { name: "Basic Reports", enabled: true },
      { name: "Broadcast", enabled: false },
      { name: "Admissions", enabled: false },
      { name: "Parent App", enabled: false },
      { name: "Online Payment", enabled: false },
    ],
  },
  {
    name: "Growth",
    annualPrice: "1,20,000",
    monthlyPrice: "12,000",
    studentLimit: "750",
    pilotFee: "10,000",
    mostPopular: true,
    features: [
      { name: "Attendance", enabled: true },
      { name: "Fee Management", enabled: true },
      { name: "Reports", enabled: true },
      { name: "Broadcast", enabled: true },
      { name: "Admissions", enabled: true },
      { name: "Parent App", enabled: false },
      { name: "Online Payment", enabled: false },
    ],
  },
  {
    name: "Pro",
    annualPrice: "3,50,000",
    monthlyPrice: "35,000",
    studentLimit: "Unlimited",
    pilotFee: "25,000",
    features: [
      { name: "Attendance", enabled: true },
      { name: "Fee Management", enabled: true },
      { name: "All Reports", enabled: true },
      { name: "Broadcast", enabled: true },
      { name: "Admissions", enabled: true },
      { name: "Parent App", enabled: true },
      { name: "Online Payment", enabled: true },
    ],
  },
];
