import type { GeneratedReport } from "../types/reports.types";
import { FileText, Download } from "lucide-react";
import { FormatBadge } from "./Reportbadges";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHead,
  TableCell,
} from "@/components/ui/table";

// Report icon per type
const ReportIcon = ({ type }: { type: GeneratedReport["type"] }) => {
  const color: Record<string, string> = {
    ATTENDANCE: "text-indigo-500",
    FEE_COLLECTION: "text-emerald-500",
    STUDENT: "text-blue-500",
    WHATSAPP_ACTIVITY: "text-green-500",
    ADMISSIONS: "text-violet-500",
    STAFF: "text-amber-500",
  };
  return (
    <div className={`w-7 h-7 rounded-lg flex items-center justify-center bg-gray-50 ${color[type]}`}>
      <FileText className="h-4 w-4" />
    </div>
  );
};

const Avatar = ({ initials }: { initials: string }) => (
  <div className="w-7 h-7 rounded-full bg-indigo-100 flex items-center justify-center text-[10px] font-bold text-indigo-700">
    {initials}
  </div>
);

interface RecentReportsTableProps {
  reports: GeneratedReport[];
  onDownload: (id: string) => void;
}

const RecentReportsTable = ({ reports, onDownload }: RecentReportsTableProps) => (
  <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
    <div className="overflow-x-auto">
      <Table>
        <TableHeader>
          <TableRow>
            {[
              "Report Name",
              "Generated On",
              "Period",
              "Format",
              "Generated By",
              "Download",
            ].map(h => (
              <TableHead key={h} className="px-5 py-3.5 text-[10px] font-bold uppercase tracking-widest text-gray-400">
                {h}
              </TableHead>
            ))}
          </TableRow>
        </TableHeader>
        <TableBody>
          {reports.map((report, i) => (
            <TableRow
              key={report.id}
              className={`border-b border-gray-50 hover:bg-gray-50/60 transition-colors ${
                i === reports.length - 1 ? "border-b-0" : ""
              }`}
            >
              <TableCell className="px-5 py-4">
                <div className="flex items-center gap-3">
                  <ReportIcon type={report.type} />
                  <span className="text-sm font-semibold text-gray-800">{report.reportName}</span>
                </div>
              </TableCell>
              <TableCell className="px-5 py-4 text-xs text-gray-500">{report.generatedOn}</TableCell>
              <TableCell className="px-5 py-4 text-xs text-gray-600 font-medium">{report.period}</TableCell>
              <TableCell className="px-5 py-4">
                <FormatBadge format={report.format} />
              </TableCell>
              <TableCell className="px-5 py-4">
                <div className="flex items-center gap-2">
                  <Avatar initials={report.generatedBy.initials} />
                  <span className="text-xs text-gray-600 font-medium">{report.generatedBy.name}</span>
                </div>
              </TableCell>
              <TableCell className="px-5 py-4">
                <Button
                  type="button"
                  variant="ghost"
                  size="sm"
                  onClick={() => onDownload(report.id)}
                  className="w-8 h-8 rounded-lg border border-gray-200 text-gray-500 hover:text-indigo-600 hover:border-indigo-300 hover:bg-indigo-50 transition-colors p-0"
                >
                  <Download className="h-4 w-4" />
                </Button>
              </TableCell>
            </TableRow>
          ))}
        </TableBody>
      </Table>
    </div>
  </div>
);

export default RecentReportsTable;