import type { GeneratedReport } from "../types/reports.types";
import { FormatBadge } from "./Reportbadges";

// Report icon per type
const ReportIcon = ({ type }: { type: GeneratedReport["type"] }) => {
  const color: Record<string, string> = {
    ATTENDANCE: "text-indigo-500",
    FEE_COLLECTION: "text-emerald-500",
    STUDENT: "text-blue-500",
    WHATSAPP_ACTIVITY: "text-green-500",
    ADMISSIONS: "text-violet-500",
    STAFF: "text-amber-500",
  };
  return (
    <div className={`w-7 h-7 rounded-lg flex items-center justify-center bg-gray-50 ${color[type]}`}>
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
        <polyline points="14 2 14 8 20 8" />
        <line x1="16" y1="13" x2="8" y2="13" />
        <line x1="16" y1="17" x2="8" y2="17" />
        <polyline points="10 9 9 9 8 9" />
      </svg>
    </div>
  );
};

const Avatar = ({ initials }: { initials: string }) => (
  <div className="w-7 h-7 rounded-full bg-indigo-100 flex items-center justify-center text-[10px] font-bold text-indigo-700">
    {initials}
  </div>
);

interface RecentReportsTableProps {
  reports: GeneratedReport[];
  onDownload: (id: string) => void;
}

const RecentReportsTable = ({ reports, onDownload }: RecentReportsTableProps) => (
  <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
    <div className="overflow-x-auto">
      <table className="w-full text-left">
        <thead>
          <tr className="border-b border-gray-100">
            {["Report Name", "Generated On", "Period", "Format", "Generated By", "Download"].map(h => (
              <th key={h} className="px-5 py-3.5 text-[10px] font-bold uppercase tracking-widest text-gray-400">
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {reports.map((report, i) => (
            <tr
              key={report.id}
              className={`border-b border-gray-50 hover:bg-gray-50/60 transition-colors ${
                i === reports.length - 1 ? "border-b-0" : ""
              }`}
            >
              <td className="px-5 py-4">
                <div className="flex items-center gap-3">
                  <ReportIcon type={report.type} />
                  <span className="text-sm font-semibold text-gray-800">{report.reportName}</span>
                </div>
              </td>
              <td className="px-5 py-4 text-xs text-gray-500">{report.generatedOn}</td>
              <td className="px-5 py-4 text-xs text-gray-600 font-medium">{report.period}</td>
              <td className="px-5 py-4">
                <FormatBadge format={report.format} />
              </td>
              <td className="px-5 py-4">
                <div className="flex items-center gap-2">
                  <Avatar initials={report.generatedBy.initials} />
                  <span className="text-xs text-gray-600 font-medium">{report.generatedBy.name}</span>
                </div>
              </td>
              <td className="px-5 py-4">
                <button
                  onClick={() => onDownload(report.id)}
                  className="w-8 h-8 rounded-lg border border-gray-200 flex items-center justify-center text-gray-500 hover:text-indigo-600 hover:border-indigo-300 hover:bg-indigo-50 transition-colors"
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                    <polyline points="7 10 12 15 17 10" />
                    <line x1="12" y1="15" x2="12" y2="3" />
                  </svg>
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  </div>
);

export default RecentReportsTable;