import type { GeneratedReport } from "../types/reports.types";
import { FileText, Download } from "lucide-react";
import { FormatBadge } from "./Reportbadges";
import { Button } from "@/components/ui/button";
import {
  Table,
  TableHeader,
  TableBody,
  TableRow,
  TableHead,
  TableCell,
} from "@/components/ui/table";

// ── Report icon per type ──────────────────────────────────────────────────────

const ReportIcon = ({ type }: { type: GeneratedReport["type"] }) => {
  const color: Record<string, string> = {
    ATTENDANCE:         "text-indigo-500 bg-indigo-50",
    FEE_COLLECTION:     "text-emerald-500 bg-emerald-50",
    STUDENT:            "text-blue-500 bg-blue-50",
    WHATSAPP_ACTIVITY:  "text-green-500 bg-green-50",
    ADMISSIONS:         "text-violet-500 bg-violet-50",
    STAFF:              "text-amber-500 bg-amber-50",
  };
  return (
    <div
      className={`w-7 h-7 sm:w-8 sm:h-8 rounded-lg flex-shrink-0 flex items-center justify-center ${color[type] ?? "text-gray-500 bg-gray-50"}`}
    >
      <FileText className="h-3.5 w-3.5 sm:h-4 sm:w-4" />
    </div>
  );
};

// ── Avatar ────────────────────────────────────────────────────────────────────

const Avatar = ({ initials }: { initials: string }) => (
  <div className="w-7 h-7 flex-shrink-0 rounded-full bg-indigo-100 flex items-center justify-center text-[10px] font-bold text-indigo-700 select-none">
    {initials}
  </div>
);

// ── Mobile card (shown on xs screens) ────────────────────────────────────────

interface MobileCardProps {
  report: GeneratedReport;
  onDownload: (id: string) => void;
}

const MobileCard = ({ report, onDownload }: MobileCardProps) => (
  <div className="flex items-start justify-between gap-3 px-4 py-4 border-b border-gray-100 last:border-b-0">
    {/* Left: icon + details */}
    <div className="flex items-start gap-3 min-w-0">
      <ReportIcon type={report.type} />
      <div className="min-w-0">
        <p className="text-sm font-semibold text-gray-800 truncate leading-snug">
          {report.reportName}
        </p>
        <p className="text-xs text-gray-400 mt-0.5">{report.generatedOn}</p>
        <div className="flex flex-wrap items-center gap-2 mt-1.5">
          <span className="text-xs text-gray-500 font-medium">{report.period}</span>
          <FormatBadge format={report.format} />
        </div>
        <div className="flex items-center gap-1.5 mt-1.5">
          <Avatar initials={report.generatedBy?.initials ?? "?"} />
          <span className="text-xs text-gray-500">{report.generatedBy?.name ?? "Unknown"}</span>
        </div>
      </div>
    </div>

    {/* Right: download */}
    <Button
      type="button"
      variant="ghost"
      size="sm"
      onClick={() => onDownload(report.id)}
      aria-label={`Download ${report.reportName}`}
      className="flex-shrink-0 w-8 h-8 rounded-lg border border-gray-200 text-gray-400 hover:text-indigo-600 hover:border-indigo-300 hover:bg-indigo-50 transition-colors p-0 mt-0.5"
    >
      <Download className="h-4 w-4" />
    </Button>
  </div>
);

// ── Main component ────────────────────────────────────────────────────────────

interface RecentReportsTableProps {
  reports: GeneratedReport[];
  onDownload: (id: string) => void;
}

const RecentReportsTable = ({ reports, onDownload }: RecentReportsTableProps) => (
  <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden w-full">

    {/* ── Mobile view (< md) ── */}
    <div className="md:hidden">
      {reports.length === 0 ? (
        <p className="px-4 py-8 text-center text-sm text-gray-400">No reports found.</p>
      ) : (
        reports.map((report) => (
          <MobileCard key={report.id} report={report} onDownload={onDownload} />
        ))
      )}
    </div>

    {/* ── Desktop table (≥ md) ── */}
    <div className="hidden md:block overflow-x-auto">
      <Table className="w-full min-w-[640px]">
        <TableHeader>
          <TableRow className="border-b border-gray-100">
            {[
              { label: "Report Name",   cls: "" },
              { label: "Generated On",  cls: "whitespace-nowrap" },
              { label: "Period",        cls: "" },
              { label: "Format",        cls: "" },
              { label: "Generated By",  cls: "" },
              { label: "Download",      cls: "text-right pr-5" },
            ].map(({ label, cls }) => (
              <TableHead
                key={label}
                className={`px-5 py-3.5 text-[10px] font-bold uppercase tracking-widest text-gray-400 ${cls}`}
              >
                {label}
              </TableHead>
            ))}
          </TableRow>
        </TableHeader>

        <TableBody>
          {reports.length === 0 ? (
            <TableRow>
              <TableCell colSpan={6} className="px-5 py-10 text-center text-sm text-gray-400">
                No reports found.
              </TableCell>
            </TableRow>
          ) : (
            reports.map((report, i) => (
              <TableRow
                key={report.id}
                className={`hover:bg-gray-50/60 transition-colors ${
                  i === reports.length - 1 ? "border-b-0" : "border-b border-gray-50"
                }`}
              >
                {/* Report name */}
                <TableCell className="px-5 py-4">
                  <div className="flex items-center gap-3 min-w-0">
                    <ReportIcon type={report.type} />
                    <span className="text-sm font-semibold text-gray-800 truncate max-w-[180px] lg:max-w-none">
                      {report.reportName}
                    </span>
                  </div>
                </TableCell>

                {/* Generated on */}
                <TableCell className="px-5 py-4 text-xs text-gray-500 whitespace-nowrap">
                  {report.generatedOn}
                </TableCell>

                {/* Period */}
                <TableCell className="px-5 py-4 text-xs text-gray-600 font-medium whitespace-nowrap">
                  {report.period}
                </TableCell>

                {/* Format badge */}
                <TableCell className="px-5 py-4">
                  <FormatBadge format={report.format} />
                </TableCell>

                {/* Generated by */}
                <TableCell className="px-5 py-4">
                  <div className="flex items-center gap-2 min-w-0">
                    <Avatar initials={report.generatedBy?.initials ?? "?"} />
                    <span className="text-xs text-gray-600 font-medium truncate max-w-[100px] lg:max-w-none">
                      {report.generatedBy?.name ?? "Unknown"}
                    </span>
                  </div>
                </TableCell>

                {/* Download */}
                <TableCell className="px-5 py-4 text-right">
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    onClick={() => onDownload(report.id)}
                    aria-label={`Download ${report.reportName}`}
                    className="w-8 h-8 rounded-lg border border-gray-200 text-gray-500 hover:text-indigo-600 hover:border-indigo-300 hover:bg-indigo-50 active:scale-95 transition-all p-0 ml-auto"
                  >
                    <Download className="h-4 w-4" />
                  </Button>
                </TableCell>
              </TableRow>
            ))
          )}
        </TableBody>
      </Table>
    </div>
  </div>
);

export default RecentReportsTable;