import { format, parseISO } from "date-fns";
import type { ReportRecord } from "../types/reports.types";
import { ReportIcons } from "../utils/report-config";
import { FormatBadge, StatusBadge } from "./ReportBadges";
import Pagination from "./Pagination";
import { useDownloadReport } from "../hooks/useReports";

interface RecentReportsTableProps {
  records: ReportRecord[];
  isLoading: boolean;
  total: number;
  page: number;
  pageSize: number;
  onPageChange: (p: number) => void;
  onViewAll: () => void;
}

const COL = "text-[11px] font-semibold uppercase tracking-widest text-gray-400 px-4 py-3 text-left";

const RecentReportsTable = ({
  records, isLoading, total, page, pageSize, onPageChange, onViewAll,
}: RecentReportsTableProps) => {
  const { download, loadingId } = useDownloadReport();

  const DownloadIcon = () => (
    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round">
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
      <polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/>
    </svg>
  );

  if (isLoading) {
    return (
      <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-6">
        <div className="flex items-center justify-between mb-5">
          <div className="h-5 w-36 rounded bg-gray-100 animate-pulse" />
          <div className="h-4 w-24 rounded bg-gray-100 animate-pulse" />
        </div>
        {[...Array(4)].map((_, i) => (
          <div key={i} className="flex gap-4 py-4 border-b border-gray-50 last:border-0 animate-pulse">
            <div className="w-8 h-8 rounded-lg bg-gray-100 flex-shrink-0" />
            <div className="flex-1 space-y-2">
              <div className="h-3 w-32 rounded bg-gray-100" />
              <div className="h-2.5 w-20 rounded bg-gray-100" />
            </div>
            <div className="w-12 h-5 rounded bg-gray-100" />
            <div className="w-16 h-6 rounded-full bg-gray-100" />
            <div className="w-20 h-4 rounded bg-gray-100" />
          </div>
        ))}
      </div>
    );
  }

  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
      {/* Section header */}
      <div className="flex items-center justify-between px-5 py-4 border-b border-gray-50">
        <h2 className="text-base font-extrabold text-gray-900">Recent Reports</h2>
        <button
          onClick={onViewAll}
          className="text-sm font-semibold text-indigo-600 hover:text-indigo-800 transition-colors"
        >
          View All History
        </button>
      </div>

      {/* Table */}
      <div className="overflow-x-auto">
        <table className="w-full min-w-[700px]">
          <thead>
            <tr className="border-b border-gray-50">
              <th className={COL}>Report Name</th>
              <th className={COL}>Generated By</th>
              <th className={COL}>Date</th>
              <th className={COL}>Period</th>
              <th className={COL}>Format</th>
              <th className={COL}>Status</th>
              <th className={COL}>Action</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-50">
            {records.map((r) => {
              const Icon = ReportIcons[r.type];
              const isDownloading = loadingId === r.id;
              return (
                <tr key={r.id} className="hover:bg-gray-50/60 transition-colors">
                  {/* Report name + icon */}
                  <td className="px-4 py-4">
                    <div className="flex items-center gap-3">
                      <div className="w-8 h-8 rounded-lg bg-indigo-50 text-indigo-600 flex items-center justify-center flex-shrink-0">
                        <Icon size={15} />
                      </div>
                      <span className="text-sm font-semibold text-gray-900 leading-tight">{r.name}</span>
                    </div>
                  </td>

                  <td className="px-4 py-4 text-sm text-gray-500">{r.generatedBy}</td>

                  <td className="px-4 py-4 text-sm text-gray-500 whitespace-nowrap">
                    {format(parseISO(r.date), "MMM dd, yyyy")}
                  </td>

                  <td className="px-4 py-4 text-sm text-gray-500 whitespace-nowrap">{r.period}</td>

                  <td className="px-4 py-4"><FormatBadge format={r.format} /></td>

                  <td className="px-4 py-4"><StatusBadge status={r.status} /></td>

                  <td className="px-4 py-4">
                    {r.status === "READY" ? (
                      <button
                        onClick={() => download(r.id, r.name, r.format)}
                        disabled={isDownloading}
                        className="inline-flex items-center gap-1.5 text-sm font-bold text-indigo-600 hover:text-indigo-800 disabled:opacity-50 transition-colors"
                      >
                        <DownloadIcon />
                        {isDownloading ? "…" : "Download"}
                      </button>
                    ) : (
                      <span className="text-xs text-gray-400">—</span>
                    )}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* Pagination footer */}
      <div className="px-5 py-4 border-t border-gray-50">
        <Pagination
          page={page}
          total={total}
          pageSize={pageSize}
          onChange={onPageChange}
        />
      </div>
    </div>
  );
};

export default RecentReportsTable;
