import type {
  ClassTimetable,
  UpcomingExaminations,
  TimetableRow,
} from "../types/Classtimetable.types";

export const mockTimetable: ClassTimetable = {
  className: "Class 10A",
  academicYear: "2024-25",
  todayDay: "Monday",
  subjects: [
    { name: "English",       color: "bg-blue-50",   dotColor: "bg-blue-400"   },
    { name: "Maths",         color: "bg-green-50",  dotColor: "bg-green-500"  },
    { name: "Physics",       color: "bg-sky-50",    dotColor: "bg-sky-500"    },
    { name: "Chemistry",     color: "bg-purple-50", dotColor: "bg-purple-400" },
    { name: "Biology",       color: "bg-emerald-50",dotColor: "bg-emerald-500"},
    { name: "Social Studies",color: "bg-yellow-50", dotColor: "bg-yellow-500" },
    { name: "Hindi",         color: "bg-pink-50",   dotColor: "bg-red-500"    },
  ],
  rows: [
    {
      kind: "period",
      periodNumber: 1,
      startTime: "08:30",
      endTime: "09:20",
      days: {
        Monday:    { subject: "English",        teacher: "Priya Reddy",  isActive: true },
        Tuesday:   { subject: "Chemistry",      teacher: "Padma K"      },
        Wednesday: { subject: "Maths",          teacher: "Anand Rao"    },
        Thursday:  { subject: "Physics",        teacher: "S. Sharma"    },
        Friday:    { subject: "Biology",        teacher: "Dr. Mehta"    },
        Saturday:  { subject: "FREE",           note: "Library"         },
      },
    },
    {
      kind: "period",
      periodNumber: 2,
      startTime: "09:20",
      endTime: "10:10",
      days: {
        Monday:    { subject: "Maths",          teacher: "Anand Rao"    },
        Tuesday:   { subject: "Social Studies", teacher: "R. Singh"     },
        Wednesday: { subject: "Hindi",          teacher: "Sneh Lata"    },
        Thursday:  { subject: "English",        teacher: "Priya Reddy"  },
        Friday:    { subject: "Chemistry",      teacher: "Padma K"      },
        Saturday:  { subject: "Physics",        teacher: "S. Sharma"    },
      },
    },
    {
      kind: "break",
      label: "SHORT BREAK",
      startTime: "10:10",
      endTime: "10:30",
    },
    {
      kind: "period",
      periodNumber: 3,
      startTime: "10:30",
      endTime: "11:15",
      days: {
        Monday:    { subject: "Physics",        teacher: "S. Sharma"    },
        Tuesday:   { subject: "Maths",          teacher: "Anand Rao"    },
        Wednesday: { subject: "Chemistry",      teacher: "Padma K"      },
        Thursday:  { subject: "Biology",        teacher: "Dr. Mehta"    },
        Friday:    { subject: "Social Studies", teacher: "R. Singh"     },
        Saturday:  { subject: "Maths",          teacher: "Anand Rao"    },
      },
    },
    {
      kind: "break",
      label: "LUNCH BREAK",
      startTime: "12:00",
      endTime: "12:45",
    },
    {
      kind: "period",
      periodNumber: 4,
      startTime: "12:45",
      endTime: "13:30",
      days: {
        Monday:    { subject: "FREE",           note: "Common Room"     },
        Tuesday:   { subject: "English",        teacher: "Priya Reddy"  },
        Wednesday: { subject: "Physics",        teacher: "S. Sharma"    },
        Thursday:  { subject: "Maths",          teacher: "Anand Rao"    },
        Friday:    { subject: "Hindi",          teacher: "Sneh Lata"    },
        Saturday:  { subject: "English",        teacher: "Priya Reddy"  },
      },
    },
  ] as TimetableRow[],
};

export const mockExaminations: UpcomingExaminations = {
  title: "Unit Test 1",
  exams: [
    {
      id: "EX001",
      subject: "English",
      date: "Oct 14, 2024",
      day: "Monday",
      timeFrom: "09:00",
      timeTo: "11:30 AM",
      venue: "Main Hall - Block A",
    },
    {
      id: "EX002",
      subject: "Maths",
      date: "Oct 15, 2024",
      day: "Tuesday",
      timeFrom: "09:00",
      timeTo: "11:30 AM",
      venue: "Maths Lab - Floor 2",
    },
    {
      id: "EX003",
      subject: "Science",
      date: "Oct 16, 2024",
      day: "Wednesday",
      timeFrom: "09:00",
      timeTo: "11:30 AM",
      venue: "Science Wing - Lab 03",
    },
    {
      id: "EX004",
      subject: "Social Studies",
      date: "Oct 17, 2024",
      day: "Thursday",
      timeFrom: "09:00",
      timeTo: "11:30 AM",
      venue: "Main Hall - Block A",
    },
    {
      id: "EX005",
      subject: "Hindi",
      date: "Oct 18, 2024",
      day: "Friday",
      timeFrom: "09:00",
      timeTo: "11:30 AM",
      venue: "Classroom 10A",
    },
  ],
};