import type {
  AttendanceDay,
  AttendanceHistory,
  HolidayCalendar,
  MarkAttendanceForm,
} from "../types/attendance.types";

// ─── Today's Attendance ──────────────────────────────────────────────────────
export const mockAttendanceToday: AttendanceDay = {
  date: "2025-04-07",
  summary: {
    totalPresent: 318,
    totalPresentChange: 2.4,
    totalAbsent: 24,
    totalAbsentChange: 9.8,
    classesMarked: 12,
    classesTotal: 15,
    alertsSent: 24,
    alertsTotal: 24,
  },
  classes: [
    {
      classSec: "6A",
      teacherName: "Priya Reddy",
      teacherInitials: "PR",
      teacherColor: "#6366F1",
      total: 34,
      present: 32,
      absent: 2,
      status: "MARKED",
      method: "WhatsApp",
      alertsSent: 2,
      alertsTotal: 2,
    },
    {
      classSec: "6B",
      teacherName: "Sita Rao",
      teacherInitials: "SR",
      teacherColor: "#8B5CF6",
      total: 32,
      present: 30,
      absent: 2,
      status: "MARKED",
      method: "Web Form",
      alertsSent: 2,
      alertsTotal: 2,
    },
    {
      classSec: "7A",
      teacherName: "Kiran Kumar",
      teacherInitials: "KK",
      teacherColor: "#10B981",
      total: 30,
      present: 28,
      absent: 2,
      status: "MARKED",
      method: "WhatsApp",
      alertsSent: 2,
      alertsTotal: 2,
    },
    {
      classSec: "8A",
      teacherName: "Suresh M",
      teacherInitials: "SM",
      teacherColor: "#F59E0B",
      total: 30,
      present: null,
      absent: null,
      status: "NOT_MARKED",
      method: null,
      alertsSent: 0,
      alertsTotal: 0,
    },
    {
      classSec: "9A",
      teacherName: "Raju T",
      teacherInitials: "RT",
      teacherColor: "#EF4444",
      total: 29,
      present: null,
      absent: null,
      status: "NOT_MARKED",
      method: null,
      alertsSent: 0,
      alertsTotal: 0,
    },
    {
      classSec: "10A",
      teacherName: "Venkat R",
      teacherInitials: "VR",
      teacherColor: "#3B82F6",
      total: 33,
      present: null,
      absent: null,
      status: "NOT_MARKED",
      method: null,
      alertsSent: 0,
      alertsTotal: 0,
    },
  ],
};

// ─── History ────────────────────────────────────────────────────────────────
export const mockAttendanceHistory: AttendanceHistory = {
  dateRange: { from: "2025-03-01", to: "2025-04-07" },
  selectedClass: "All Classes",
  monthlyAverage: 92.4,
  improvementFromLastMonth: 2.1,
  trendData: [
    { date: "05MAR", class6A: 95, class7A: 88, class8A: 82, avg: 88 },
    { date: "10MAR", class6A: 93, class7A: 90, class8A: 80, avg: 87 },
    { date: "15MAR", class6A: 91, class7A: 87, class8A: 83, avg: 87 },
    { date: "20MAR", class6A: 94, class7A: 92, class8A: 79, avg: 88 },
    { date: "25MAR", class6A: 96, class7A: 89, class8A: 77, avg: 87 },
    { date: "30MAR", class6A: 95, class7A: 91, class8A: 81, avg: 89 },
    { date: "05APR", class6A: 97, class7A: 93, class8A: 75, avg: 88 },
    { date: "07APR", class6A: 94, class7A: 93, class8A: 76, avg: 88 },
  ],
  actionRequired: {
    className: "10A",
    message:
      "Class 10A has fallen below the 85% attendance threshold for 3 consecutive days. A review meeting is suggested.",
  },
  chronicAbsentees: [
    {
      id: "CA001",
      name: "Ravi Teja",
      initials: "RT",
      avatarColor: "#EF4444",
      className: "10A",
      absentDays: 8,
      absentSeverity: "high",
      lastAbsent: "Today",
      parentPhone: "+91 96765 43210",
    },
    {
      id: "CA002",
      name: "Priya S",
      initials: "PS",
      avatarColor: "#6366F1",
      className: "9B",
      absentDays: 6,
      absentSeverity: "medium",
      lastAbsent: "5 Apr",
      parentPhone: "+91 87664 32109",
    },
    {
      id: "CA003",
      name: "Kiran R",
      initials: "KR",
      avatarColor: "#10B981",
      className: "8A",
      absentDays: 6,
      absentSeverity: "medium",
      lastAbsent: "4 Apr",
      parentPhone: "+91 76543 21098",
    },
    {
      id: "CA004",
      name: "Suresh N",
      initials: "SN",
      avatarColor: "#F59E0B",
      className: "7B",
      absentDays: 5,
      absentSeverity: "low",
      lastAbsent: "3 Apr",
      parentPhone: "+91 65432 10987",
    },
    {
      id: "CA005",
      name: "Anitha D",
      initials: "AD",
      avatarColor: "#8B5CF6",
      className: "6A",
      absentDays: 5,
      absentSeverity: "low",
      lastAbsent: "2 Apr",
      parentPhone: "+91 54321 09876",
    },
    {
      id: "CA006",
      name: "Venkat R",
      initials: "VR",
      avatarColor: "#3B82F6",
      className: "10B",
      absentDays: 5,
      absentSeverity: "low",
      lastAbsent: "1 Apr",
      parentPhone: "+91 43210 98765",
    },
  ],
};

// ─── Holiday Calendar ────────────────────────────────────────────────────────
export const mockHolidayCalendar: HolidayCalendar = {
  month: "April",
  year: 2025,
  totalHolidaysThisYear: 12,
  academicYear: "2024-25",
  holidays: [
    { id: "H001", name: "School Day", date: "2025-04-01", type: "SCHOOL_DAY" },
    { id: "H002", name: "Ambedkar Jayanti", date: "2025-04-14", type: "NATIONAL_HOLIDAY" },
    { id: "H003", name: "Good Friday", date: "2025-04-18", type: "PUBLIC_HOLIDAY" },
    { id: "H004", name: "School Sports Day", date: "2025-04-21", type: "SCHOOL_EVENT" },
  ],
};

// ─── Mark Attendance Web Form ────────────────────────────────────────────────
export const mockMarkAttendanceForm: MarkAttendanceForm = {
  class: "Class 8A",
  section: "A",
  date: "2025-04-07",
  students: [
    { rollNo: "01", name: "Aravind Kumar", isPresent: true },
    { rollNo: "02", name: "Divya Rao", isPresent: true },
    { rollNo: "03", name: "Mohammed Adil", isPresent: true },
    { rollNo: "04", name: "Suresh Nair", isPresent: false },
    { rollNo: "05", name: "Priya Sharma", isPresent: true },
    { rollNo: "06", name: "Arjun Patel", isPresent: true },
    { rollNo: "07", name: "Ananya Singh", isPresent: true },
    { rollNo: "08", name: "Rahul Mehta", isPresent: true },
    { rollNo: "09", name: "Sneha Reddy", isPresent: true },
    { rollNo: "10", name: "Vijay Kumar", isPresent: true },
    { rollNo: "11", name: "Lakshmi Devi", isPresent: true },
    { rollNo: "12", name: "Rohan Gupta", isPresent: true },
    { rollNo: "13", name: "Pooja Nair", isPresent: true },
    { rollNo: "14", name: "Arun Sharma", isPresent: true },
    { rollNo: "15", name: "Meena Pillai", isPresent: true },
    { rollNo: "16", name: "Deepak Rao", isPresent: true },
    { rollNo: "17", name: "Kavita Singh", isPresent: true },
    { rollNo: "18", name: "Sanjay Patel", isPresent: true },
    { rollNo: "19", name: "Rekha Menon", isPresent: true },
    { rollNo: "20", name: "Nikhil Joshi", isPresent: true },
    { rollNo: "21", name: "Swati Verma", isPresent: true },
    { rollNo: "22", name: "Karthik Iyer", isPresent: true },
    { rollNo: "23", name: "Divya Krishnan", isPresent: true },
    { rollNo: "24", name: "Sunil Bhat", isPresent: true },
    { rollNo: "25", name: "Anita Thomas", isPresent: true },
    { rollNo: "26", name: "Ravi Teja", isPresent: true },
    { rollNo: "27", name: "Preethi Nair", isPresent: true },
    { rollNo: "28", name: "Ganesh Kumar", isPresent: true },
    { rollNo: "29", name: "Sunitha Reddy", isPresent: true },
    { rollNo: "30", name: "Mohan Das", isPresent: true },
  ],
};
